Repository TaleStation/TaleStation-Wiki, pull requests merged in 2024-01, with the labels that each got.

#8 Adds the wiki home page
  README.md
Labels: Information Update

#9 Finishes off the Getting Started page with more information
  general/getting_started.md
Labels: 📄 Information Update

#10 Fix a singular typo in the readme
  README.md
Labels: ✍️ Grammar
